### ISSUE TITLE
How should I use it?

### ISSUE THREAD

**Issue by ganlanyuan** [PascalAOMS/dynamic-polyfill#1]
Just put the code below into `head`, 
```javascript
<script src="node_modules/dynamic-polyfill/src/index.js"></script>
<script>
  import polyfill from dynamic-polyfill
   
  polyfill({
      fills: 'fetch, Promise',
      options: 'gated',
      minify: false,
      afterFill() {
          main();
      }
  });
  function main() {
    alert('abc');
  }
</script>
```
but get two errors:
```javascript
SyntaxError: export declarations may only appear at top level of a module
SyntaxError: import declarations may only appear at top level of a module
```
Am I doing something wrong?

**Comment by PascalAOMS** [comment]
As of right now only Edge supports ES6 modules. 
You need a bundler like Webpack or Browserify to use import/export statements.

Put `import polyfill from 'dynamic-polyfill'` in your main JS file and run it through the bundler.

**Comment by ganlanyuan** [comment]
Thanks for the quick response,
Do I still need put the index.js into `head`?
```javascript
<script src="node_modules/dynamic-polyfill/src/index.js"></script>
```

**Comment by PascalAOMS** [comment]
When working with bundlers, all you need to do is `import` the NPM packages you want to use into your main JS files. 

So no, no need for script tags. :)

**Comment by ganlanyuan** [comment]
Great!
Thanks for the reply

**Comment by PascalAOMS** [comment]
If you need some tips in setting up Webpack, feel free to send me an email.

Wish you great holidays.

**Comment by ganlanyuan** [comment]
Okay, I will.
Thanks again and happy holidays!
