### ISSUE TITLE
Could you make a es5 version of this plugin?

### ISSUE THREAD

**Issue by ganlanyuan** [PascalAOMS/dynamic-polyfill#3]
Just noticed that webpack 2 dropped IE8 support. 
Could you make a es5 version of this plugin? So that people couldn't use webpack 2 (due to IE8 supporting) still benefit from it.
Thanks a lot!

**Comment by PascalAOMS** [comment]
Sorry that you still have to support IE8.

Thanks for your question, I did not know that it would restrict the usage in a big way (still quite new to all this stuff).

I'll look into it.

**Comment by ganlanyuan** [comment]
Thanks

**Comment by PascalAOMS** [comment]
Just a little heads-up. I will upload a new version on the weekend.

**Comment by ganlanyuan** [comment]
Great, thanks a lot!

**Comment by PascalAOMS** [comment]
I am sorry but I will not be able to support IE8.
Methods like `reduce` had to be used which are only supported in IE9+.

If you really need IE8 support consider putting a script tag of the polyfill.io API in your body.
