### ISSUE TITLE
Illegal invocation upon checking Element.prototype.classList

### ISSUE THREAD

**Issue by kontrollanten** [PascalAOMS/dynamic-polyfill#6]
Thanks for a great module!

I issued a problem upon adding `Element.prototype.classList` to polyfills:
```
Uncaught TypeError: Illegal invocation
    at index.js:28
    at Array.reduce (<anonymous>)
```
Which is happening in [on this line](https://github.com/PascalAOMS/dynamic-polyfill/blob/master/src/index.js#L18).

I created a solution that could work for this case, based on [this](https://jsperf.com/checknested-efficiency):

```
function checkNestedFast(obj /*, level1, level2, ... levelN*/) {
    for (var i = 1; i < arguments.length; i++) {
      if (!obj.hasOwnProperty(arguments[i])) {
        return false;
      }
      if (i !== arguments.length - 1) {
        obj = obj[arguments[i]];
      }
    }
    return true;
  }
```

I don't have time to create PR right now. But I hope I can fix it during the weekend.

**Comment by PascalAOMS** [comment]
Thank you for your report.

Another solution could be to see if `Element` is part of the string and check this way: 
```js
'Element' in window && 'classList' in Element.prototype
```

You would not need to specify `classList`. This is just an example.

**Comment by PascalAOMS** [comment]
Uploaded a patch. Hope this fixes your issue.

**Comment by kontrollanten** [comment]
It works great! Thanks for your quick update!
